version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
    - REDIS_DNS=redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000