name: Deploy and Test application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      shell: /usr/bin/bash -e {0}
      env:
        KUBECONFIG: /home/runner/work/_temp/kubeconfig_1692563521034

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: List files in kubernetes directory
      run: ls -l kubernetes

    - name: Deploy application
      run: kubectl --kubeconfig kubeconfig apply -f kubernetes

    - name: Wait for deployment
      run: kubectl rollout status deployment

    - name: Run test script
      run: |
        chmod +x ci/test_script.sh
        ci/test_script.sh
